CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_MEMBER(
   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_EMAIL VARCHAR2(255) NOT NULL,
   MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
   MEMBER_NAME VARCHAR2(255) NOT NULL,
   MEMBER_AGE NUMBER DEFAULT 0,
   MEMBER_GENDER VARCHAR2(255) DEFAULT 3,
   CREATED_DATE DATE DEFAULT SYSDATE,
   UPDATED_DATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'YHH725@NAVER.COM', '1234', 'YHJ', 25, 1, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'LJM123@GAMAIL.COM', '4321', 'LJM', 24, 1, SYSDATE, SYSDATE);

INSERT INTO TBL_MEMBER
(ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_MEMBER.NEXTVAL, 'YBR@NAVER.COM', '2631', 'YBR', 21, 2, SYSDATE, SYSDATE);

SELECT *FROM TBL_MEMBER;


CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
    POST_TITLE VARCHAR2(255) NOT NULL,
    POST_CONTENT VARCHAR2(255) NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
    REFERENCES TBL_MEMBER(ID),
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE
);


INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_POST.NEXTVAL, '자바', '클래스', 2, SYSDATE, SYSDATE);

INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_POST.NEXTVAL, 'DBMS', 'DML', 3, SYSDATE, SYSDATE);

INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, MEMBER_ID, CREATED_DATE, UPDATED_DATE)
VALUES(SEQ_POST.NEXTVAL, 'GIT', 'GITHUB', 1, SYSDATE, SYSDATE);

SELECT *FROM TBL_POST; 


SELECT P.ID, P.POST_TITLE, P.POST_CONTENT, P.MEMBER_ID,M.MEMBER_NAME, P.CREATED_DATE ,P.UPDATED_DATE 
FROM TBL_POST P  JOIN TBL_MEMBER M
ON P.MEMBER_ID =M.ID;










